### ISSUE TITLE
Unable to run the app, issue with "svelte-loader" module

### ISSUE THREAD

**Issue by vredrav** [sveltejs/realworld#10]
I am running the master branch.
There appears to be an issue with the Svelte-loader node_module.
```
compiler.hooks.watchRun.tapAsync('VirtualModulesPlugin', (watcher, callback) => { // compiler.hooks is undefined
		this._watcher = watcher.compiler || watcher;
		callback();
	});
```
Getting the following error in the console:
```
(node:81352) UnhandledPromiseRejectionWarning: ./routes/index.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/.../node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/.../node_modules/svelte-loader/index.js:83:46)
 @ ./.sapper/server-entry.js 1:0-111
(node:81352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

Need resolution on this. Has anybody else run in the same issue? how do I resolve this?

**Comment by vredrav** [comment]
This is an issue with the svelte-loader module. I was able to get it to run by downgrading the svelte-loader version to 2.8.1

There is an issue opened with the module  - https://github.com/sveltejs/svelte-loader/issues/63

**Comment by QuantumInformation** [comment]
Can this be closed now?
