### ISSUE TITLE
Fetch failed

### ISSUE THREAD

**Issue by shinokada** [sveltejs/realworld#146]
Installed a fresh realworld and starting the server returns `fetch failed`.

```
npm run dev

> realworld.svelte.dev@1.0.1-next.0 dev
> vite dev


Forced re-optimization of dependencies

  VITE v3.2.4  ready in 446 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
fetch failed
TypeError: fetch failed
    at fetch (/Users/shinichiokada/Svelte/realworld/node_modules/undici/index.js:105:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async send (/src/lib/api.js:17:14)
    at async Promise.all (index 1)
    at async load (/src/routes/+page.server.js:18:50)
    at async load_server_data (file:///Users/shinichiokada/Svelte/realworld/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:33:17)
    at async file:///Users/shinichiokada/Svelte/realworld/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:142:13
fetch failed
TypeError: fetch failed
    at fetch (/Users/shinichiokada/Svelte/realworld/node_modules/undici/index.js:105:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async send (/src/lib/api.js:17:14)
    at async Promise.all (index 0)
    at async load (/src/routes/+page.server.js:18:50)
    at async load_server_data (file:///Users/shinichiokada/Svelte/realworld/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:33:17)
    at async file:///Users/shinichiokada/Svelte/realworld/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:142:13
```

System info:

```
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 366.63 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Chrome: 107.0.5304.110
    Chrome Canary: 110.0.5430.0
    Firefox: 107.0
    Safari: 16.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.553 
    svelte: ^3.52.0 => 3.53.1 
    vite: ^3.2.2 => 3.2.4 
```

**Comment by shinokada** [comment]
I'm not sure what's going on here. But this morning when I start it, it is working. So I close this for now.
