### ISSUE TITLE
npm install and npm run dev are not wokring in latest realworld project

### ISSUE THREAD

**Issue by alokmahor** [sveltejs/realworld#149]
Yesterday I took fresh clone and tried to run usual commands

`git clone https://github.com/sveltejs/realworld`
`npm install` #failed
`npm install --force` # worked
`npm run dev` # failed

Here is output
```
PS D:\tmp\test-svelte> git clone https://github.com/sveltejs/realworld
Cloning into 'realworld'...
remote: Enumerating objects: 1802, done.
remote: Counting objects: 100% (717/717), done.
remote: Compressing objects: 100% (386/386), done.
Receiving objects: 100% (1802/1802), 909.96 KiB | 946.00 KiB/s, done.
remote: Total 1802 (delta 372), reused 569 (delta 284), pack-reused 1085
Resolving deltas: 100% (929/929), done.
PS D:\tmp\test-svelte> cd .\realworld\
PS D:\tmp\test-svelte\realworld> code .
PS D:\tmp\test-svelte\realworld> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: realworld.svelte.dev@1.0.1-next.0
npm ERR! Found: vite@3.2.5
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.2.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^4.0.0" from @sveltejs/kit@1.0.0-next.582
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"next" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\alokm\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alokm\AppData\Local\npm-cache\_logs\2022-12-11T02_38_30_411Z-debug-0.log
PS D:\tmp\test-svelte\realworld> npm install --force
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @sveltejs/kit@1.0.0-next.582
npm WARN Found: vite@3.2.5
npm WARN node_modules/vite
npm WARN   peer vite@"^4.0.0" from @sveltejs/vite-plugin-svelte@2.0.0
npm WARN   node_modules/@sveltejs/kit/node_modules/@sveltejs/vite-plugin-svelte
npm WARN     @sveltejs/vite-plugin-svelte@"^2.0.0" from @sveltejs/kit@1.0.0-next.582
npm WARN     node_modules/@sveltejs/kit
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer vite@"^4.0.0" from @sveltejs/kit@1.0.0-next.582
npm WARN node_modules/@sveltejs/kit
npm WARN   dev @sveltejs/kit@"next" from the root project
npm WARN
npm WARN Conflicting peer dependency: vite@4.0.0
npm WARN node_modules/vite
npm WARN   peer vite@"^4.0.0" from @sveltejs/kit@1.0.0-next.582
npm WARN   node_modules/@sveltejs/kit
npm WARN     dev @sveltejs/kit@"next" from the root project

added 122 packages, and audited 123 packages in 51s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS D:\tmp\test-svelte\realworld> npm run dev

> realworld.svelte.dev@1.0.1-next.0 dev
> vite dev

failed to load config from D:\tmp\test-svelte\realworld\vite.config.js
error when starting dev server:
file:///D:/tmp/test-svelte/realworld/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:6
import { isCSSRequest } from 'vite';
         ^^^^^^^^^^^^
SyntaxError: The requested module 'vite' does not provide an export named 'isCSSRequest'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadConfigFromBundledFile (file:///D:/tmp/test-svelte/realworld/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:63135:21)
    at async loadConfigFromFile (file:///D:/tmp/test-svelte/realworld/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:63020:28)
    at async resolveConfig (file:///D:/tmp/test-svelte/realworld/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:62643:28)
    at async createServer (file:///D:/tmp/test-svelte/realworld/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:61943:20)
    at async CAC.<anonymous> (file:///D:/tmp/test-svelte/realworld/node_modules/vite/dist/node/cli.js:707:24)
PS D:\tmp\test-svelte\realworld>
```

**Comment by benmccann** [comment]
Fixed
