### ISSUE TITLE
Cannot find module 'api.js'

### ISSUE THREAD

**Issue by M4v3R** [sveltejs/realworld#18]
Pulled from the latest master, did a clean `npm install`, while running the app I get many errors like:

```
'api.js' is imported by src/routes/index.svelte, but could not be resolved – treating it as an external dependency
```

And then at the end:

```
module.js:538
    throw err;
    ^

Error: Cannot find module 'api.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mav/Documents/flyps/realworld/__sapper__/dev/server/server.js:13:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
> Server crashed
```

**Comment by Sebring** [comment]
You can peek the old file in the repo here before it was deleted.
https://github.com/sveltejs/realworld/commit/3c61ad463ea002ab3faa33a1f2f3227972abc2fe#diff-17e46da7586caf4f665a809c16049d6b

**Comment by toby3d** [comment]
@Sebring This does not solve the problem:
<details>
<summary>Details</summary>

```bash
> npm run dev

> svelte-realworld@0.0.1 dev /home/toby3d/git/realworld
> sapper dev

• client
'api.js' is imported by src/routes/index.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/article/[slug].svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/article/_ArticleMeta.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/editor/[slug].svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/editor/_Editor.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/article/_Comment.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/article/_CommentInput.svelte, but could not be resolved – treating it as an external dependency
'utils.js' is imported by src/routes/register/index.svelte, but could not be resolved – treating it as an external dependency
'utils.js' is imported by src/routes/settings/index.svelte, but could not be resolved – treating it as an external dependency
'utils.js' is imported by src/routes/login/index.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/profile/[user]/index.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/profile/[user]/[view].svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/profile/[user]/_Profile.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/_components/ArticleList/index.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/_components/ArticleList/ArticlePreview.svelte, but could not be resolved – treating it as an external dependency
• server
'api.js' is imported by src/routes/index.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/auth/register.js, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/auth/login.js, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/auth/save.js, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/article/[slug].svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/article/_ArticleMeta.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/editor/[slug].svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/editor/_Editor.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/article/_Comment.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/article/_CommentInput.svelte, but could not be resolved – treating it as an external dependency
'utils.js' is imported by src/routes/register/index.svelte, but could not be resolved – treating it as an external dependency
'utils.js' is imported by src/routes/settings/index.svelte, but could not be resolved – treating it as an external dependency
'utils.js' is imported by src/routes/login/index.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/profile/[user]/index.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/profile/[user]/[view].svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/profile/[user]/_Profile.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/_components/ArticleList/index.svelte, but could not be resolved – treating it as an external dependency
'api.js' is imported by src/routes/_components/ArticleList/ArticlePreview.svelte, but could not be resolved – treating it as an external dependency
'del' is imported from external module 'api.js' but never used
✔ service worker (34ms)
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'api.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/toby3d/git/realworld/__sapper__/dev/server/server.js:13:11)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
> Server crashed
```
</details>

**Comment by Sebring** [comment]
Did you re-create `api.js`?

Looks like you need to do the same to `util.js`

**Comment by M4v3R** [comment]
@Sebring @toby3d it does work, I needed to copy the contents of `_api.js` file and paste it into `/src/node_modules/api.js`, and then also replace `import { post } from 'utils.js';` with `import { post } from 'api.js';` in three files: 

* `src/routes/login/index.svelte`
* `src/routes/register/index.svelte`
* `src/routes/settings/index.svelte`

**Comment by anndream** [comment]
> @Sebring @toby3d it does work, I needed to copy the contents of `_api.js` file and paste it into `/src/node_modules/api.js`, and then also replace `import { post } from 'utils.js';` with `import { post } from 'api.js';` in three files:
> 
> * `src/routes/login/index.svelte`
> * `src/routes/register/index.svelte`
> * `src/routes/settings/index.svelte`

it ok but can't login

**Comment by toby3d** [comment]
@M4v3R I reproduce your fixes and find 404 on editor and profile pages.

**Comment by QuantumInformation** [comment]
404 on editor page 
<img width="624" alt="Screenshot 2019-06-22 at 12 32 49" src="https://user-images.githubusercontent.com/216566/59963356-f8902d80-94e9-11e9-9bff-635311e515ce.png">

**Comment by QuantumInformation** [comment]
On the live demo

**Comment by pjholmes** [comment]
The problem is that src/routes/login/index.svelte makes a call to 'auth/login'. This call is handled on the server, which make a minor adjustment to the JSON and forwards it to the Conduit server (I'm not sure why, perhaps just to demonstrate some providing a server API). The calls in api.js will always prefix that uri with https://conduit.productionready.io/api. So, the calls were going to 'auth/login' on the Conduit server and there is no such URI.  I've created a pull request to address this.  But there may be a better place to put api.js and utils.js to reduce all of the "../../.." in the relative references.

**Comment by Conduitry** [comment]
The missing files have been added in da253e498fb0b38e15f5184c2fafaade3e857093
